name: osu-api

services:
  flask:
    build: .
    volumes:
      - osu-bancho:/.data
    networks:
      - default
      - osu-mysql
      - osu-nginx
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:latest
    user: root
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT_NUMBER: ${REDIS_PORT}
    restart: unless-stopped

volumes:
  redis-data:
  osu-bancho:
    name: osu-bancho
    external: true

networks:
  osu-mysql:
    external: true
  osu-nginx:
    external: true
