name: test-osu-api

services:
  flask:
    env_file: ".env.testing"
    build: .
    command: "pytest tests"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    env_file: ".env.testing"
    image: bitnami/redis:latest
    user: root

  mysql:
    env_file: ".env.testing"
    image: mysql:latest
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
